blank_issues_enabled: false
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/flaventu/survivops/discussions"
    about: "Join the conversation and ask questions about the project."
